### PR TITLE
chore: bump runner to node 16

### PR DESCRIPTION
**Pull request by gaber85**
This bumps the runner to node 16 as node 12 actions are now deprecated.

### CODE REVIEW

**Comment by ohmer** [comment]
LGTM, how can it be tested?

**Comment by gaber85** [comment]
> LGTM, how can it be tested?

@ohmer I've tested it via a test branch on the react repo. Here are the results: https://github.com/sharesight/react/actions/runs/4119788257/jobs/7113845323. It resolved all the warnings for this action 👍

**Comment by ohmer** [comment]
I think the package version should be bumped to 2.0.0.

Less sure about it but wouldn't it make sense to configure TS to generate for Node 16? Maybe use https://www.npmjs.com/package/@tsconfig/node16?

**Comment by gaber85** [comment]
> I think the package version should be bumped to 2.0.0.
> 
> Less sure about it but wouldn't it make sense to configure TS to generate for Node 16? Maybe use https://www.npmjs.com/package/@tsconfig/node16?

@ohmer The package version bumps needs to happen on a separate PR once we are ready to create a release manually.

We could bump the tsconfig to 2021 it but it's not really necessary, I believe the compiler we are using wants indicated es2015 support for now. We can do this on another PR.

**Pull request merged**
